[[battles]]
name="Test Battle"
combatant_a = "Suit"
combatant_b = "Shinigami"
terrain = "Lake Tampua"

[[battles]]
name="First Battle"
combatant_a = "LCEnzo"
combatant_b = "Suit"
terrain = "Hela"

[[battles]]
name="Test Terrain Badaxsan"
combatant_a = "LCEnzo"
combatant_b = "LCEnzo"
terrain = "Badaxsan"

[[battles]]
name="First Battle v2"
combatant_a = "LCEnzo"
combatant_b = "Shinigami"
terrain = "Lake Tampua"